# Generated by Django 4.1 on 2022-08-30 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0002_state_persons_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='cr.state', verbose_name='Статус'),
        ),
    ]
